development:
  adapter: postgresql
  database: my_user_hub_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: my_user_hub_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_user_hub_production
  pool: 5
  timeout: 5000
